definitions:
  dto.ErrorResponse:
    properties:
      errorMsgs:
        items:
          type: string
        type: array
      statusCode:
        type: integer
    type: object
  dto.SuccessResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  dto.UrlListResponseDTO:
    properties:
      short_url:
        type: string
      url:
        type: string
    type: object
  dto.UrlShortenRequestDTO:
    properties:
      custom_short:
        type: string
      url:
        type: string
    type: object
  dto.UrlShortenResponseDTO:
    properties:
      short_url:
        type: string
      url:
        type: string
    type: object
  dto.UserLoginRequestDTO:
    properties:
      password:
        type: string
      username_or_email:
        type: string
    type: object
  dto.UserRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.UserResponseDTO:
    properties:
      email:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a REST API for a URL shortener service.
  title: URL Shortener API
  version: "1.0"
paths:
  /{short}:
    get:
      description: Resolves a short URL to its original URL and redirects the user
      parameters:
      - description: Bearer Token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Shortened URL identifier
        in: path
        name: short
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Redirects to the original URL
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Resolve Short URL
      tags:
      - Url
  /api/v1/urls:
    delete:
      description: Delete the short for given url
      parameters:
      - description: Bearer Token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      - description: The URL for which the short URL should be deleted
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete Short By Url
      tags:
      - Url
    get:
      description: List the all urls and their short for the user
      parameters:
      - description: Bearer Token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/dto.UrlListResponseDTO'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: List Urls ans shorts for the User
      tags:
      - Url
  /api/v1/urls/shorten:
    post:
      description: Creates a custom short for given URL
      parameters:
      - description: Bearer Token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body for creating a short URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UrlShortenRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UrlShortenResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create Short for a URL
      tags:
      - Url
  /api/v1/user/{username}:
    delete:
      description: Delete user from username
      parameters:
      - description: Bearer Token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Username of the user
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete user by username
      tags:
      - User
    get:
      description: Getting user details from username
      parameters:
      - description: Bearer Token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Username of the user
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get user details by username
      tags:
      - User
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: User logs in and a token is returned
      parameters:
      - description: Login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: User Login
      tags:
      - User
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: Creates a user account with a username, email, and password
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new user
      tags:
      - User
swagger: "2.0"
